### ISSUE TITLE
about DRIVER.m file

### ISSUE THREAD

**Issue by yanyanxinshi** [MRK4863/Underwater-image-colour-colrrection-and-enhancement--using-retinex-methods-#1]
Hi, when I run the DRIVER.m file, at line 7： i = [img img(:, end-847:end, :)]; it says "The index for position 2 is invalid. The array index must be a positive integer or a logical value". How can I solve this problem please?

**Comment by MRK4863** [comment]
Line 7 is image specific, it is just extending the same image in order to match a particular dimension required by RETINEX code. 
It is basically just reflection of the same image about the RIGHT and BOTTOM axis (respectively) of the image, in order to minimize difference in gradient when computed.
Based on your input image, you can customize Line 7 & 8 to make the image dimension equal to next greater the power of 2.

Hope this data helps...

**Comment by yanyanxinshi** [comment]
Ok, thank you for informing me, I will try it, thanks again
